core/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import DetailView, ListView

from core.models import Program


urlpatterns = patterns('core.views',
	# Examples:
	# url(r'^$', 'verkiezingen.views.home', name='home'),
	# url(r'^verkiezingen/', include('verkiezingen.foo.urls')),

	url(r'^$', ListView.as_view(
			queryset=Program.objects.all().order_by('-party'),
			template_name='core/index.html')),
	url(r'^(?P<pk>\d+)/$', DetailView.as_view(
			queryset=Program.objects.select_related(),
			template_name='core/program.html'),
			name='program_view'),
)

programtracker/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import DetailView, ListView
from django.contrib.auth.views import login, logout

from core.models import Program, Section

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'verkiezingen.views.home', name='home'),
	# url(r'^verkiezingen/', include('verkiezingen.foo.urls')),

	url(r'^$', ListView.as_view(
		queryset=Program.objects.all().order_by('-party'),
		template_name='core/index.html')),

    url(r'^api/v1/', include('api.urls')),
	url(r'^program/', include('core.urls')),
	url(r'^topic/', include('topic.urls')),
	url(r'^lda/', include('lda.urls')),
	url(r'^sicco/', include('sicco.urls')),
	url(r'^keywords/', include('keywords.urls')),
	url(r'^import/', include('importdata.urls')),
	url(r'^stat/', include('statistics.urls')),
	
	url(r'^section/(?P<pk>\d+)/$', DetailView.as_view(
			model=Section,
			template_name='core/section.html'),
			name='section_view'),


	# Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
	
	url(r'^accounts/login/$',  login),
	url(r'^accounts/logout/$', logout),

)

urlpatterns += staticfiles_urlpatterns()

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import DetailView, ListView
from django.contrib.auth.views import login, logout

from core.models import Program, Section

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'verkiezingen.views.home', name='home'),
	# url(r'^verkiezingen/', include('verkiezingen.foo.urls')),

	url(r'^$', ListView.as_view(
		queryset=Program.objects.all().order_by('-party'),
		template_name='core/index.html')),
	
	url(r'^program/', include('core.urls')),
	url(r'^topic/', include('topic.urls')),
	url(r'^lda/', include('lda.urls')),
	url(r'^sicco/', include('sicco.urls')),
	url(r'^keywords/', include('keywords.urls')),
	url(r'^import/', include('importdata.urls')),
	
	url(r'^section/(?P<pk>\d+)/$', DetailView.as_view(
			model=Section,
			template_name='core/section.html'),
			name='section_view'),


	# Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
	
	url(r'^accounts/login/$',  login),
	url(r'^accounts/logout/$', logout),
)

urlpatterns += staticfiles_urlpatterns()

core/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

# Create your models here.
class Party(models.Model):
	name = models.CharField(max_length=200)
	full_name = models.CharField(max_length=200)
	pm_id = models.CharField(max_length=100)
	
	class Meta:
		verbose_name_plural = "parties"

	def __unicode__(self):
		return self.name

class Program(models.Model):
	date = models.DateField()
	party = models.ForeignKey(Party, related_name='programs')
	name = models.CharField(max_length=200, default='')
	
	class Meta:
		get_latest_by = "date"

	def __unicode__(self):
		return u'%s (%s %s)' % (self.name, self.party, self.date)
		
	@models.permalink
	def get_absolute_url(self):
		return ('program_view', [str(self.id)])

class SectionType(models.Model):
	name = models.CharField(max_length=50)

	def __unicode__(self):
		return self.name

class Section(MPTTModel):
	name = models.CharField(max_length=200)
	program = models.ForeignKey(Program, blank=True, null=True, related_name='sections')
	parent = TreeForeignKey('self', null=True, blank=True, related_name='subsections')
	type = models.ForeignKey(SectionType, default=1)
	order = models.IntegerField(default=0)
	
	class Meta:
		ordering = ['order']

	class MPTTMeta:
		order_insertion_by = ['order']

	def __unicode__(self):
		return u'Sectie %s uit %s' % (self.name, self.program)

	
	@property
	def text(self):
		return self.name + "\n" + "\n\n".join(p.text for p in self.paragraphs.all().order_by('order'))
		
	def save(self, *args, **kwargs):
		# Only modify number if creating for the first time (is default 0)
		if self.order == 0:
			# Grab the highest current index (if it exists)
			try:
				recent = Section.objects.filter(parent__exact=self.parent).order_by('-order')[0]
				self.order = recent.order + 1
			except IndexError:
				self.order = 1
		# Call the "real" save() method
		super(Section, self).save(*args, **kwargs)



class Paragraph(models.Model):
	text = models.TextField()
	section = models.ForeignKey(Section, related_name='paragraphs')
	order = models.IntegerField(default=0)
	class Meta:
		ordering = ['order']


	def __unicode__(self):
		return u'Paragraaf %s uit %s' % (self.order, self.section)

	def save(self, *args, **kwargs):
		# Only modify number if creating for the first time (is default 0)
		if self.order == 0:
			# Grab the highest current index (if it exists)
			try:
				recent = Paragraph.objects.filter(section__exact=self.section).order_by('-order')[0]
				self.order = recent.order + 1
			except IndexError:
				self.order = 1
		# Call the "real" save() method
		super(Paragraph, self).save(*args, **kwargs)

core/templates/core/counts.html
{% for count in counts %}{% if count.number > 1 %}{{ count.number }} {% for index, c in count.pcounts %}{{ index }}:{{c}} {% endfor %}
{% endif %}{% endfor %} 

core/templates/core/index.html
{% extends "base.html" %}

{% block title %}Programma's{% endblock %}

{% block content %}
<h1>Programma's</h1>
{% if program_list %}
    <ul>
    {% regroup program_list|dictsort:"date" by date as program_list_grouped %}
		{% for date in program_list_grouped %}
		    <li>{{ date.grouper }}
		    <ul>
		        {% for program in date.list %}
		          <li>
		          	<a href="/program/{{ program.id }}/">
		          		{{ program.party }}: {{program.name}}
		          	</a>
		          </li>
		        {% endfor %}
		    </ul>
		    </li>
		{% endfor %}
    </ul>
{% else %}
    <p>No parties are available.</p>
{% endif %}
{% endblock %}

core/templates/core/program.html
{% extends "base.html" %}

{% load mptt_tags %}
{% load markup %}

{% block title %}Het programma {{ program.name }}{% endblock %}

{% block content %}
	{% if program %}
		<div id="program">
		
			<p><em>Selecteer een stuk tekst om een onderwerp op te geven</em></p>
		
			{% recursetree program.sections.all %}
				<div class="{{ node.type.name }}">
					<h{{node.level|add:"1"}} class="head" id="s{{node.id}}">
						{{ node.name }}  {% if node.level = 0 %} ({{ program.party }}) {% endif %}
					</h{{node.level|add:"1"}}>
					
					{% for paragraph in node.paragraphs.all %}
						<div id="{{paragraph.id}}" class="p">
							{{ paragraph.text|markdown }}
							<div class="topics">
								{% for selection in paragraph.selections.all %}
							       
										<div style="background-color: {{selection.source.color}}" 
											class="topic" id="{{selection.id}}" 
											topic:start="{{selection.startLetter}}"
											topic:end="{{selection.endLetter}}" 
											title="{{selection.topic.description}}">
											<a href="/topic/{{selection.topic.id}}/">{{selection.topic.name}}</a>
										</div>
								{% endfor %}
							</div>
						</div>
					{% endfor %}
					
					{{ children }}
				</div>
			{% endrecursetree %}
		</div>
		<div id="topiclabel">
			Vul hier een label in: <br />
			<form method="post" action="/topic/addLabel/">{% csrf_token %}
				<input type="text" name="label" /> <input type="submit" value="Ok">
				<input type="hidden" name="start" />
				<input type="hidden" name="end" />
				<input type="hidden" name="pid" />
			</form>
		</div>
	{% else %}
		<p>No sections available.</p>
	{% endif %}
{% endblock %}


{% block submenu %}
<ul>
	{% recursetree program.sections.all %}
	 <li>
            <a href="#s{{node.id}}">{{ node.name }}</a>
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}
        </li>
	{% endrecursetree %}
</ul>

{% endblock %}

core/templates/core/words.html
{% for word in words %}{{ word }}
{% endfor %}