programtracker/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import DetailView, ListView
from django.contrib.auth.views import login, logout

from core.models import Program, Section

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'verkiezingen.views.home', name='home'),
	# url(r'^verkiezingen/', include('verkiezingen.foo.urls')),

	url(r'^$', ListView.as_view(
		queryset=Program.objects.all().order_by('-party'),
		template_name='core/index.html')),

    url(r'^api/v1/', include('api.urls')),
	url(r'^program/', include('core.urls')),
	url(r'^topic/', include('topic.urls')),
	url(r'^lda/', include('lda.urls')),
	url(r'^sicco/', include('sicco.urls')),
	url(r'^keywords/', include('keywords.urls')),
	url(r'^import/', include('importdata.urls')),
	url(r'^stat/', include('statistics.urls')),
	
	url(r'^section/(?P<pk>\d+)/$', DetailView.as_view(
			model=Section,
			template_name='core/section.html'),
			name='section_view'),


	# Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
	
	url(r'^accounts/login/$',  login),
	url(r'^accounts/logout/$', logout),

)

urlpatterns += staticfiles_urlpatterns()

topic/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import DetailView, ListView

from topic.models import Selection, Topic

urlpatterns = patterns('topic.views',
	# Examples:
	# url(r'^$', 'verkiezingen.views.home', name='home'),
	# url(r'^verkiezingen/', include('verkiezingen.foo.urls')),

	url(r'^addLabel/$', 'addLabel'),
	url(r'^$', ListView.as_view(
			queryset=Topic.objects.all().order_by('-source', 'name'),
			template_name='topic/index.html')),
	url(r'^(?P<pk>\d+)/$', DetailView.as_view(model=Topic), name='topic_view'),
	url(r'^getTopics/$', 'getTopics')
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import DetailView, ListView
from django.contrib.auth.views import login, logout

from core.models import Program, Section

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'verkiezingen.views.home', name='home'),
	# url(r'^verkiezingen/', include('verkiezingen.foo.urls')),

	url(r'^$', ListView.as_view(
		queryset=Program.objects.all().order_by('-party'),
		template_name='core/index.html')),
	
	url(r'^program/', include('core.urls')),
	url(r'^topic/', include('topic.urls')),
	url(r'^lda/', include('lda.urls')),
	url(r'^sicco/', include('sicco.urls')),
	url(r'^keywords/', include('keywords.urls')),
	url(r'^import/', include('importdata.urls')),
	
	url(r'^section/(?P<pk>\d+)/$', DetailView.as_view(
			model=Section,
			template_name='core/section.html'),
			name='section_view'),


	# Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
	
	url(r'^accounts/login/$',  login),
	url(r'^accounts/logout/$', logout),
)

urlpatterns += staticfiles_urlpatterns()

topic/models.py
from django.db import models

# Create your models here.
class Source(models.Model):
	name = models.CharField(max_length=200)
	color = models.CharField(max_length=20, default="#ffccff")
	
	def __unicode__(self):
		return u'%s' % (self.name)

class Thesaurus(Source):
	pass


class Topic(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField()
	creationdate = models.DateField(auto_now_add=True);
	source = models.ForeignKey(Source, related_name='topics', blank=True, null=True)
	thesaurus = models.ForeignKey(Thesaurus, related_name='ttopics', blank=True, null=True)

	
	def __unicode__(self):
		return u'%s' % (self.name)
		
	@models.permalink
	def get_absolute_url(self):
		return ('topic_view', [str(self.id)])	

class Selection(models.Model):
	paragraph = models.ForeignKey('core.Paragraph', related_name='selections')
	source = models.ForeignKey(Source, related_name='selections', blank=True, null=True)
	startLetter = models.IntegerField(default=0)
	endLetter = models.IntegerField(default=-1)
	topic = models.ForeignKey(Topic, related_name='selections')
	user = models.ForeignKey('auth.User', blank=True, null=True)
	creationdate = models.DateField(auto_now_add=True);
	extra = models.CharField(max_length=100, blank=True, null=True)

	def __unicode__(self):
		return u'%s: ((%s) van %s tot %s)' % (self.topic, self.paragraph, self.startLetter, self.endLetter)
		
	def prefix(self):
		return self.paragraph.text[:self.startLetter]
		
	def text(self):
		if self.endLetter < 0:
			return self.paragraph.text
		else:
			return self.paragraph.text[self.startLetter:self.endLetter]
		
	def postfix(self):
		if self.endLetter < 0:
			return ''
		else:
			return self.paragraph.text[self.endLetter:]

topic/views.py
from django.http import HttpResponse
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
from topic.models import Selection, Topic, Source
from django.utils import simplejson

# Create your views here.

def addLabel(request):
	if request.is_ajax() and request.method == 'POST':
		label = request.POST['label']

		if request.user.is_authenticated():
			user = request.user
		else:
			user = None
		source, created = Source.objects.get_or_create(name = 'user')

		t, created = Topic.objects.get_or_create(name = label, source = source)
		
		s = Selection.objects.create(
			paragraph_id = request.POST['pid'],
			startLetter = request.POST['start'],
			endLetter = request.POST['end'],
			source = source,
			user = user,
			topic = t,)
		
		if request.user.is_authenticated():
			result = {"start":s.startLetter, "end": s.endLetter, 'label': label, 'id': s.id, 'source_color':s.source.color, 'topic_name': t.name, 'topic_id': t.id, 'topic_desc': t.description}
		else:
			result = {"start":s.startLetter, "end": s.endLetter, 'label': label, 'id': s.id, 'source_color':s.source.color, 'topic_name': t.name, 'topic_id': t.id, 'topic_desc': t.description}
		
		
		message = simplejson.dumps(result)
		mimetype = 'application/json'
	else:
		message = "No XHR"
		mimetype = 'text/html'
	return HttpResponse(message, mimetype)


def getTopics(request):
	if not request.is_ajax():
		term = request.GET.get('term', '')
		topics = list(Topic.objects.filter(name__istartswith=term).order_by('name').values_list('name', flat=True))
		
		message = simplejson.dumps(topics)
		mimetype = 'application/json'
	else:
		message = "No XHR"
		mimetype = 'text/html'
	return HttpResponse(message, mimetype)

topic/templates/topic/index.html
{% extends "base.html" %}

{% block title %}Programma's{% endblock %}

{% block content %}
<h1>Topics</h1>
{% if topic_list %}
    <ul>
    {% regroup topic_list by source as topic_list_grouped %}
		{% for source in topic_list_grouped %}
		    <li>{{ source.grouper }}
		    <ul>
		        {% for topic in source.list %}
		          <li>
		          	<a href="/topic/{{ topic.id }}/">
		          		{{ topic.name }}
		          	</a>
		          </li>
		        {% endfor %}
		    </ul>
		    </li>
		{% endfor %}
    </ul>
{% else %}
    <p>No parties are available.</p>
{% endif %}
{% endblock %}

topic/templates/topic/source_list.html
{% extends "base.html" %}

{% block title %}Topic sources{% endblock %}

{% block content %}
<h1>Topic sources</h1>
{% if source_list %}
    <ul>
    {% for source in source_list %}
        <li><a href="{% url statistics.views.sourceindex source.id %}">{{ source.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No sources are available.</p>
{% endif %}
{% endblock %}

topic/templates/topic/topic_detail.html
{% extends "base.html" %}

{% load markup %}

{% block title %}Topic {{topic.name}}{% endblock %}

{% block content %}
	{% if topic %}
		<div id="program">
			<h1>{{topic.name}}</h1>
			<p>{{topic.description}}</p>
			{% for selection in topic.selections.all %}
				<h3><a href="/program/{{selection.paragraph.section.program.id}}/#{{selection.paragraph.id}}">
					{{ selection.paragraph.section.program.party.name}}: {{ selection.paragraph.section.program.name}}
					</a>
				</h3>
				
				<p class="selected" topic:start="{{selection.startLetter}}" topic:end="{{selection.endLetter}}">	{{ selection.paragraph.text|markdown }} 
				</p>
			{% endfor %}
		</div>
	{% else %}
		<p>No topic available.</p>
	{% endif %}
{% endblock %}

topic/templates/topic/topic_list.html
{% extends "base.html" %}

{% block title %}Topic's{% endblock %}

{% block content %}
<h1>Topic's</h1>
{% if topic_list %}
    <ul>
    {% for topic in topic_list %}
        <li><a href="/topic/{{ topic.id}}/">{{ topic.name }}</a> <span class="description">{{topic.description}}</span></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No topics are available.</p>
{% endif %}
{% endblock %}